import SolowModel from './SolowModel';
import SimulationIntro from 'src/components/SimulationIntro';

export default function SolowModelContainer() {
  // eslint-disable-next-line
  const intro = (
    <div style={{
      textAlign: 'left',
    }}>
      <p>
        One of the primary goals of macroeconomics is to understand the drivers of long run economic growth. Part of this question is why some countries grow more quickly than others, while another part deals more with the long-run “destination” to which countries may be heading. The Solow model approaches these questions by considering the roles of capital accumulation, diminishing marginal returns, and the concept of a “steady state.” First, we'll consider how output is generated by using inputs to produce output- all the stuff we like to eat, use, and live in. Then, we'll try to understand how capital can play a key role in expanding the size of the economic pie for everyone. Finally, we'll explore the limits of production and capital accumulation in growing the economy.
      </p>
      <p>
        First up, production. Just like in our first model, we're going to assume our economy uses capital and labor to make the things we consume. We're also still going to use the Cobb-Douglas functional form since it typically matches pretty well with the data when we think about the whole economy added together, and it has those nice mathematical properties we talked about in the production model, that make it so we can solve this thing without a computer. The only difference now is that we're going to be thinking about how things change over time, so we're adding time subscripts to the variables so that we know <strong>when</strong> we are as well.
      </p>
      <p style={{ textAlign: 'center', }}>
        Production equation here (1)
      </p>
      <p>
        Next, we need to keep track of what we do with that production every period. We're going to assume that all we do is either consume production (eat it), or we save it to make more consumption next period (invest it). This is called a resource constraint, and you might recognize it from intro when you talked about GDP being made up of consumption, investment, government spending, and net exports. For now, we're going to make a simplifying assumption that there is no government, and our economy isn't trading with any others.
      </p>
      <p style={{ textAlign: 'center', }}>
        Accounting equation here (2)
      </p>
      <p>
        Now we get to talk about the way that those savings can get us more capital, and therefore help our economy grow. This is called the capital accumulation equation. It says that the amount of capital we have <strong>tomorrow</strong> is determined by how much we have <strong>today</strong>, plus the amount we've saved instead of eaten <strong>today</strong>, minus anything we lost to depreciation. Depreciation can be things like machines getting worn down and needing to be replaced, damage through use of buildings and cars, or in our eating economy, maybe this is food you left out in the sun that the birds stole, or spoiled before you could eat it. We're going to assume that cumulatively, some amount (Greek letter lower case delta) of our capital today will not be available tomorrow.
      </p>
      <p style={{ textAlign: 'center', }}>
        Capital accumulation equation here (3)
      </p>
      <p>
        This equation is really the driver in the Solow model because it is the only one that tells us about how we go from one time period to the next one- notice it has both t and t+1 while all the others only have t. The nice thing about equation (3) is that we can also re write it so that it tells us how much capital changes from one period to the next
      </p>
      <p style={{ textAlign: 'center', }}>
        Change in capital accumulation equation here (3a)
      </p>
      <p>
        This says that we get new capital from that savings but we lose capital from depreciation, and whether capital tomorrow is bigger than capital today depends on whether we save more or lose more. This will be important later.
      </p>
      <p>
        We still need to make a couple more simplifying assumptions and decisions to finish up the model set up. We're going to assume that the labor we use to produce our output is constant- so the population isn't growing or declining in our model. We'll talk later about relaxing this assumption, but for now, it makes our lives a lot easier. Last, but not least, we're going to say that the amount of the output that we save for later is a constant fraction of what we produce (s):
      </p>
      <p style={{ textAlign: 'center', }}>
        Investment rule equation here (4)
      </p>
      <p style={{ textAlign: 'center', }}>
        (Table with a model summary- see handwritten doc for variables, equations, parameters since word is terrible with subscripts.)
      </p>
      <p>
        We can finally get to answering those big picture questions now about how countries grow and why some grow faster than others! This is where the steady state comes in. Once we graph the equations we just outlined, we'll notice there's a point where investment and depreciation intersect- the amount we save is exactly equal to the amount we lose! If we have more capital at any given point in time than at that point, depreciation will be more than we save, and we'll lose capital until we get back to that point. But! If we have less capital than at that point, we're saving more than we lose, and the economy will grow! We call this point the steady state because if we're ever not at that point, the forces in our economy will automatically pull us back there and we'll stay there. This observation also allows us to solve our model for that spot by hand, and gives us some nice intuition for economic growth.
      </p>
    </div>
  )

  return (
    <div className="module-container">
      <SimulationIntro
        name="Solow Model"
        text={'placeholder'}
        //text={intro}
      />
      <SolowModel />
    </div>
  );
}
