
version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      # updates to nivo broke the chart synchronization in Joint Distributions
      - dependency-name: "@nivo/core"
      - dependency-name: "@nivo/scatterplot"

    # Temporarily disable dependabot updates for npm packages
    # to re-enable, remove/comment out the following line
    open-pull-requests-limit: 0

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

    # Temporarily disable dependabot updates for npm packages
    # to re-enable, remove/comment out the following line
    open-pull-requests-limit: 0
