name: Build, Test, Lint, Deploy

on:
  pull_request:
    branches: [ deployment ]
env:
  NODE_OPTIONS: '--max_old_space_size=4096'  # this should fix a build error where the javascript heap runs out of memory

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      NEXT_PUBLIC_BASE_PATH: /econsimstest
    
    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Get files
        uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm ci
      - name: Build project
        run: npm run build
      - name: Run tests
        run: npm test
      - name: Run lint
        run: npm run lint
      - name: Export static files
        run: npm run export
      - name: Add .nojekyll file
        run: touch ./out/.nojekyll
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: gh-pages
          folder: out